name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Backend Tests
      - name: Run Backend Tests
        run: |
          docker-compose exec backend pytest --junitxml=reports/backend-test-results.xml

      # Run Frontend Tests
      - name: Run Frontend Tests
        run: |
          docker-compose exec frontend npm test -- --ci --reporters=default --reporters=jest-junit --outputPath=reports/frontend-test-results.xml

      # Upload Backend Test Results
      - name: Upload Backend Test Results
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: reports/backend-test-results.xml

      # Upload Frontend Test Results
      - name: Upload Frontend Test Results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-test-results
          path: reports/frontend-test-results.xml
